Update LinuxBuild.yml

diff --git a/.github/workflows/LinuxBuild.yml b/.github/workflows/LinuxBuild.yml
--- a/.github/workflows/LinuxBuild.yml
+++ b/.github/workflows/LinuxBuild.yml
@@ -28,24 +28,29 @@ jobs:
 # ------------------------------------------------------------------------------------------------------
 # start Testing 
 # ------------------------------------------------------------------------------------------------------
-#       - name: Testing GingerUtilsTest
-#         run: dotnet test  Ginger/GingerUtilsTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
+      - name: Testing GingerUtilsTest
+        run: dotnet test  Ginger/GingerUtilsTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
+        
+      - name: 'printing file - GingerConsole.dll'
+        if: success() || failure()        # run this step even if previous step failed
+        run: | 
+          ls -alt Ginger/GingerUtilsTest 
       
-#       - name: 'Testing GingerCoreCommonTest'
-#         run: dotnet test  Ginger/GingerCoreCommonTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
+      - name: 'Testing GingerCoreCommonTest'
+        run: dotnet test  Ginger/GingerCoreCommonTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
 
-#         # for GingerCoreNET we use run setting to limit to have one worker thread due to workspace limitation
-#       - name: 'Testing GingerCoreNETUnitTest'
-#         run: dotnet test  Ginger/GingerCoreNETUnitTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
+        # for GingerCoreNET we use run setting to limit to have one worker thread due to workspace limitation
+      - name: 'Testing GingerCoreNETUnitTest'
+        run: dotnet test  Ginger/GingerCoreNETUnitTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
 
-#       - name: 'Testing GingerPluginCoreTest'
-#         run: dotnet test  Ginger/GingerPluginCoreTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
+      - name: 'Testing GingerPluginCoreTest'
+        run: dotnet test  Ginger/GingerPluginCoreTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
 
-#       - name: 'Testing GingerConsoleTest'
-#         run: dotnet test  Ginger/GingerConsoleTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
+      - name: 'Testing GingerConsoleTest'
+        run: dotnet test  Ginger/GingerConsoleTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
 
-#       - name: 'Testing GingerAutoPilotTest'
-#         run: dotnet test  Ginger/GingerAutoPilotTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
+      - name: 'Testing GingerAutoPilotTest'
+        run: dotnet test  Ginger/GingerAutoPilotTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
         
         
         
@@ -60,35 +65,15 @@ jobs:
 # ------------------------------------------------------------------------------------------------------
 # Publish Test Results
 # ------------------------------------------------------------------------------------------------------   
-#       - name: Test Report
-#         uses: dorny/test-reporter@v1
-#         if: success() || failure()        # run this step even if previous step failed
-#         with:
-#           name: Ginger Linux UnitTests    # Name of the check run which will be created
-#           path: "**/*.trx"                # Path to test results
-#           reporter: dotnet-trx            # Format of test results
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: Ginger Linux UnitTests    # Name of the check run which will be created
+          path: "**/*.trx"                # Path to test results
+          reporter: dotnet-trx            # Format of test results
       
       
-    
-    
-      - name: 'printing file - GingerRuntime.dll'
-        run: | 
-          find . -name "GingerRuntime.dll"    
-   
-   
-      - name: 'printing path'
-        run: |
-          pwd
-          ls Ginger/GingerRuntime/bin -alt
-
-      - name: 'printing path'
-        run: |
-          ls Ginger/GingerRuntime/bin/Release -alt
-          
-      - name: 'printing path'
-        run: |
-          ls Ginger/GingerRuntime/bin/Release/net6.0 -alt
- 
           
 # ------------------------------------------------------------------------------------------------------
 # Run Standalone CLI Test
